apiVersion: v1
kind: Pod
metadata:
  name: sleep-loop-pod
spec:
  serviceAccountName: image-viewer
  containers:
  - name: sleep-loop
    image: google/cloud-sdk:slim
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Sleeping...'; sleep 1; done"]
  restartPolicy: Always
